/** Clinical Aurora: overview layers aggregate PLO evidence from individual results into a calm, drill-down capable dashboard. */
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChevronRight, CircleAlert, Filter, MoreHorizontal, Search, Sparkles } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import PloBadge from "@/components/PloBadge";
import EvidenceSpine from "@/components/EvidenceSpine";
import ReportActions from "@/components/ReportActions";
import { courseRows, demoPlos, radarData, trendData } from "@/lib/demo-data";
import { loadYearAttainmentData, searchStudents, type StudentSearchResult, type YearAttainment } from "@/lib/dashboard-data";
import type { AssessmentReportRow } from "@/lib/report-utils";

const MiniStat = ({ label, value, meta, trend, tone = "azure" }: { label: string; value: string; meta: string; trend?: "up" | "down"; tone?: "azure" | "violet" | "coral" }) => <Card className={`metric-card tone-${tone}`}><CardContent><div className="metric-top"><span>{label}</span>{trend && <span className={`metric-trend ${trend}`} >{trend === "up" ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{trend === "up" ? "3.1%" : "2 คน"}</span>}</div><strong>{value}</strong><p>{meta}</p></CardContent></Card>;

const demoYearAttainment: YearAttainment[] = [
  { year: "ปี 1", students: 96, attained: 78, pending: 8 },
  { year: "ปี 2", students: 88, attained: 81, pending: 6 },
  { year: "ปี 3", students: 84, attained: 86, pending: 4 },
  { year: "ปี 4", students: 79, attained: 91, pending: 3 },
];

const dashboardReportRows: AssessmentReportRow[] = demoPlos.map((plo) => ({ studentCode: "COHORT-SUMMARY", studentName: "PLO cohort summary", yearLevel: "ทุกชั้นปี", plo: plo.code, value: plo.attainment / 20, status: plo.status, term: "2568/1", reason: `${plo.attainment}% attainment; target ${plo.target}%`, sourceEvidence: "PLO achievement aggregation" }));

function StudentSearchPanel({ demoMode, onStudent }: { demoMode: boolean; onStudent: (studentId?: string) => void }) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<StudentSearchResult[]>([]);
  const [status, setStatus] = useState<"idle" | "loading" | "live" | "empty" | "error">("idle");
  useEffect(() => {
    const normalized = query.trim();
    if (!normalized) { setResults([]); setStatus("idle"); return; }
    if (demoMode) { setResults([]); setStatus("empty"); return; }
    setStatus("loading");
    const timer = window.setTimeout(() => { void searchStudents(normalized).then((result) => { setResults(result.data); setStatus(result.status); }).catch(() => { setResults([]); setStatus("error"); }); }, 220);
    return () => window.clearTimeout(timer);
  }, [demoMode, query]);
  return <div className="student-search-panel"><div className="search-caption"><Search size={15} /><span>ค้นหานักศึกษา</span></div><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="รหัสหรือชื่อ…" aria-label="ค้นหานักศึกษาตามรหัสหรือชื่อ" />{status === "loading" && <span className="search-status">กำลังค้นหา…</span>}{status === "error" && <span className="search-status error">ค้นหาไม่สำเร็จตามสิทธิ์ของบัญชี</span>}{status === "empty" && <span className="search-status">ไม่พบข้อมูล</span>}{results.length > 0 && <div className="student-search-results">{results.map((student) => <button type="button" key={student.id} onClick={() => onStudent(student.id)}><strong>{student.student_code}</strong><span>{student.full_name_th} · ปี {student.current_year_level}</span></button>)}</div>}</div>;
}

export default function Dashboard({ onStudent, demoMode = false }: { onStudent: (studentId?: string) => void; demoMode?: boolean }) {
  const [selectedCohorts, setSelectedCohorts] = useState(["2565", "2566"]);
  const [radarMode, setRadarMode] = useState<"attainment" | "courses">("attainment");
  const [yearAttainment, setYearAttainment] = useState<YearAttainment[]>(demoMode ? demoYearAttainment : []);
  const [yearDataStatus, setYearDataStatus] = useState<"demo" | "loading" | "live" | "empty" | "error">(demoMode ? "demo" : "loading");
  const [term] = useState("2568/1");
  useEffect(() => { if (demoMode) return; loadYearAttainmentData(term).then((result) => { setYearDataStatus(result.status); setYearAttainment(result.data); }).catch(() => setYearDataStatus("error")); }, [demoMode, term]);
  const displayedRadarData = useMemo(() => radarData.map((item, index) => ({ ...item, courses: demoPlos[index].courses * 10 })), []);
  const toggleCohort = (cohort: string) => setSelectedCohorts((current) => current.includes(cohort) ? current.filter((item) => item !== cohort) : [...current, cohort]);

  return <div className="dashboard-stack">
    <section className="page-lead overview-lead">
      <div className="lead-copy"><p className="eyebrow">PROGRAMME OVERVIEW · DEMO</p><h1>ผลการบรรลุที่มองเห็น<br /><em>เส้นทางหลักฐาน</em> ชัดเจน</h1><p>ภาพรวมหลักสูตรปรับปรุง พ.ศ. 2565 ที่สรุปจากคำตัดสินรายบุคคล โดยไม่รวมสถานะยังไม่ตัดสินในตัวหาร</p></div>
      <div className="lead-art" style={{ backgroundImage: "url(https://files.manuscdn.com/user_upload_by_module/session_file/310519663912059158/dirqkzFxSvACeCuS.png)" }}><span>LeTCI-ready</span><div className="lead-orbit lead-orbit-1" /><div className="lead-orbit lead-orbit-2" /></div>
    </section>
    <EvidenceSpine items={[{ label: "คำตัดสินรายคน", detail: "2,104 verdicts" }, { label: "ภาพรวมรายรุ่น", detail: "3 cohorts" }, { label: "SAR หลักสูตร", detail: "LeTCI-ready" }]} active={1} />
    <section className="toolbar-row"><StudentSearchPanel demoMode={demoMode} onStudent={onStudent} /><div className="cohort-filter"><span className="filter-label"><Filter size={15} />ปีที่เข้า</span>{["2565", "2566", "2567"].map((cohort) => <div key={cohort} className={`cohort-chip ${selectedCohorts.includes(cohort) ? "selected" : ""}`} role="button" tabIndex={0} onClick={() => toggleCohort(cohort)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); toggleCohort(cohort); } }}><Checkbox checked={selectedCohorts.includes(cohort)} tabIndex={-1} />รุ่น {cohort}</div>)}</div><div className="toolbar-actions"><Select defaultValue="2568/1"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="2568/1">2568 / ภาค 1</SelectItem><SelectItem value="2567/2">2567 / ภาค 2</SelectItem></SelectContent></Select><ReportActions rows={dashboardReportRows} fileName="plo-dashboard-report" /></div></section>
    <section className="metrics-grid"><MiniStat label="อัตราการบรรลุ PLO" value="82.4%" meta="เป้าหมายหลักสูตร 80%" trend="up" /><MiniStat label="ยังไม่ตัดสิน" value="12 คน" meta="ผลระดับ M/P ไม่ครบ" trend="down" tone="violet" /><MiniStat label="ภาระงานเฉลี่ย" value="4.2 ชม." meta="ต่อคน · 11 ชิ้นงาน" tone="coral" /><Card className="metric-card evidence-metric"><CardContent><div className="metric-top"><span>ความพร้อมหลักฐาน</span><span className="evidence-score">92%</span></div><div className="evidence-track"><span /></div><p>ผ่าน checklist 46/50 รายการ</p></CardContent></Card></section>
    <section className="dashboard-grid year-attainment-section"><Card className="chart-card year-attainment-card"><CardContent><div className="card-heading"><div><p className="section-kicker">YEAR-LEVEL ATTAINMENT</p><h2>ผลสัมฤทธิ์ PLO แยกตามชั้นปี</h2><p className="chart-subtitle">เปรียบเทียบสัดส่วน PLO ที่บรรลุจากผลที่ตัดสินแล้ว · ภาคเรียน {term}</p></div><span className="chart-source-tag">{yearDataStatus === "demo" ? "DEMO VIEW" : yearDataStatus === "live" ? "SUPABASE LIVE" : yearDataStatus.toUpperCase()}</span></div><div className="chart-area year-chart-area">{yearDataStatus === "loading" ? <div className="year-empty-state">กำลังอ่านผลสัมฤทธิ์จาก Supabase…</div> : yearDataStatus === "empty" ? <div className="year-empty-state">ยังไม่มีผล PLO ที่ตัดสินสำหรับภาคเรียน {term}</div> : yearDataStatus === "error" ? <div className="year-empty-state">ไม่สามารถอ่านข้อมูลได้ตามสิทธิ์ของบัญชีนี้</div> : <ResponsiveContainer width="100%" height="100%"><BarChart data={yearAttainment} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="rgba(151, 172, 218, .11)" /><XAxis dataKey="year" tick={{ fill: "#8290ad", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tick={{ fill: "#8290ad", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "#111725", border: "1px solid rgba(154, 180, 255, .18)", borderRadius: 14 }} formatter={(value, name) => [`${value}%`, name === "attained" ? "บรรลุ" : "ยังไม่ตัดสิน"]} /><Bar dataKey="attained" name="บรรลุ" fill="#1a9cff" radius={[6, 6, 0, 0]} /><Bar dataKey="pending" name="Pending" fill="#ae7cff" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer>}</div><div className="year-chart-foot"><span><i className="legend-azure" />บรรลุผล (%)</span><span><i className="legend-violet" />Pending (จำนวนจุดประเมิน)</span><span className="sample-note">นักศึกษาในกลุ่ม: {yearAttainment.reduce((sum, row) => sum + row.students, 0).toLocaleString()} คน</span></div></CardContent></Card></section>
    <section className="dashboard-grid main-analytics"><Card className="chart-card radar-card"><CardContent><div className="card-heading"><div><p className="section-kicker">COHORT COMPARISON</p><h2>เรดาร์การบรรลุ PLO</h2></div><div className="segmented-control"><button className={radarMode === "attainment" ? "selected" : ""} onClick={() => setRadarMode("attainment")}>% บรรลุ</button><button className={radarMode === "courses" ? "selected" : ""} onClick={() => setRadarMode("courses")}>รายวิชา</button></div></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><RadarChart data={displayedRadarData} cx="50%" cy="50%" outerRadius="70%"><Tooltip contentStyle={{ background: "#111725", border: "1px solid rgba(154, 180, 255, .18)", borderRadius: 14 }} /><Radar name="รุ่น 2565" dataKey={radarMode === "attainment" ? "cohort2565" : "courses"} stroke="#1a9cff" fill="#1a9cff" fillOpacity={0.16} strokeWidth={2} /><Radar name="เป้าหมาย" dataKey={radarMode === "attainment" ? "target" : "target"} stroke="#ae7cff" fill="#ae7cff" fillOpacity={0.04} strokeWidth={1.5} strokeDasharray="4 4" /></RadarChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="legend-azure" />รุ่น 2565</span><span><i className="legend-violet" />เป้าหมาย</span><button onClick={() => onStudent()}>ดูรายชื่อรายคน <ChevronRight size={15} /></button></div></CardContent></Card>
      <Card className="chart-card trend-card"><CardContent><div className="card-heading"><div><p className="section-kicker">LEVEL · TREND</p><h2>แนวโน้มผลการบรรลุ</h2></div><button className="more-button" aria-label="ตัวเลือกเพิ่มเติม"><MoreHorizontal size={20} /></button></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{ top: 8, right: 0, left: -20, bottom: 0 }}><defs><linearGradient id="areaAttained" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1a9cff" stopOpacity={0.42} /><stop offset="100%" stopColor="#1a9cff" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(151, 172, 218, .11)" /><XAxis dataKey="term" tick={{ fill: "#8290ad", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis domain={[60, 100]} tick={{ fill: "#8290ad", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "#111725", border: "1px solid rgba(154, 180, 255, .18)", borderRadius: 14 }} /><Area type="monotone" dataKey="attained" name="อัตราบรรลุ" stroke="#1a9cff" fill="url(#areaAttained)" strokeWidth={2.5} /><Line type="monotone" dataKey="target" name="เป้าหมาย" stroke="#ae7cff" strokeDasharray="5 5" dot={false} /></AreaChart></ResponsiveContainer></div><div className="trend-footnote"><Sparkles size={15} /><span>ผลสูงกว่าเป้าหมายต่อเนื่อง 2 ภาคการศึกษา</span></div></CardContent></Card></section>
    <section className="dashboard-grid lower-analytics"><Card className="mapping-card"><CardContent><div className="card-heading"><div><p className="section-kicker">CONSTRUCTIVE ALIGNMENT</p><h2>แผนผังรายวิชา × PLO</h2></div><Button variant="ghost" className="text-link">ดู Mapping เต็ม <ChevronRight size={15} /></Button></div><div className="mapping-scroll"><table className="mapping-table"><thead><tr><th>รายวิชา</th>{demoPlos.map((plo) => <th key={plo.code}><span>{plo.code.replace("PLO", "P")}</span><small>{plo.courses}</small></th>)}</tr></thead><tbody>{courseRows.map((course) => <tr key={course.code}><td><strong>{course.code}</strong><span>{course.name}</span></td>{course.levels.map((level, index) => <td key={`${course.code}-${index}`}>{level ? <span className={`map-level level-${level.toLowerCase()}`}>{level}</span> : <i />}</td>)}</tr>)}</tbody></table></div><div className="mapping-caption"><span><i className="level-i" />Introduce</span><span><i className="level-r" />Reinforce</span><span><i className="level-m" />Master</span><span><i className="level-p" />Practice</span></div></CardContent></Card>
      <Card className="attention-card"><CardContent><div className="attention-orb" /><div className="attention-head"><span className="attention-icon"><CircleAlert size={19} /></span><div><p className="section-kicker">CARE QUEUE</p><h2>รายการที่ต้องติดตาม</h2></div></div><div className="attention-list"><button onClick={() => onStudent()}><div><PloBadge status="not_achieved" compact /><strong>PLO2</strong><span>18 นักศึกษา</span></div><ChevronRight size={17} /></button><button onClick={() => onStudent()}><div><PloBadge status="pending" compact /><strong>PLO10</strong><span>12 นักศึกษา</span></div><ChevronRight size={17} /></button><button><div><PloBadge status="not_achieved" compact /><strong>PLO5</strong><span>9 นักศึกษา</span></div><ChevronRight size={17} /></button></div><button className="attention-footer" onClick={() => onStudent()}>เปิดมุมมองดูแลรายบุคคล <ArrowUpRight size={16} /></button></CardContent></Card></section>
    <p className="demo-disclaimer">ข้อมูลบนหน้าจอนี้เป็นข้อมูลสาธิตสำหรับตรวจสอบรูปแบบการแสดงผลเท่านั้น ผลการตัดสินจริงต้องอ่านจากฐานข้อมูล Supabase ภายใต้สิทธิ์ผู้ใช้</p>
  </div>;
}
