/** Clinical Aurora: the individual view puts the PLO verdict first, with an unbroken evidence thread down to individual measurements. */
import { useState } from "react";
import { ChevronDown, Download, Eye, FileText, RotateCcw, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import PloBadge from "@/components/PloBadge";
import EvidenceSpine from "@/components/EvidenceSpine";
import { demoStudent } from "@/lib/demo-data";

export default function StudentView() {
  const [openPlo, setOpenPlo] = useState("PLO2");
  return <div className="student-view">
    <section className="page-lead student-lead"><div className="lead-copy"><p className="eyebrow">INDIVIDUAL VERDICT · DEMO</p><h1>คำตัดสินที่<br /><em>เริ่มจากรายบุคคล</em></h1><p>ตรวจสอบผล PLO ของนักศึกษาพร้อมที่มาของคะแนน เครื่องมือ และหลักฐาน โดยยึดกฎที่อนุมัติแล้ว</p></div><div className="student-search-card"><div className="search-caption"><Search size={16} /><span>ค้นหารหัสนักศึกษา</span></div><Input defaultValue={demoStudent.studentCode} /><Button size="icon"><Search size={17} /></Button><small>ผู้ใช้จริงเข้าดูเฉพาะขอบเขตที่ได้รับสิทธิ์</small></div></section>
    <EvidenceSpine items={[{ label: "คะแนนดิบ", detail: "เฉพาะผลล่าสุด" }, { label: "sub-PLO", detail: "ค่าเฉลี่ยถ่วงน้ำหนัก" }, { label: "PLO verdict", detail: "คำตัดสินรายบุคคล" }, { label: "แผนดูแล", detail: "ซ่อมเสริม/ติดตาม" }]} active={2} />
    <Card className="student-identity-card"><CardContent><div className="student-avatar">นศ</div><div className="identity-copy"><p className="section-kicker">STUDENT RECORD</p><h2>{demoStudent.name} <span>({demoStudent.studentCode})</span></h2><p>{demoStudent.curriculum} · ชั้นปี {demoStudent.yearLevel} · รุ่น {demoStudent.cohort}</p></div><div className="verdict-summary"><div><span className="summary-number achieved">{demoStudent.total.achieved}</span><small>ผ่าน</small></div><div><span className="summary-number failed">{demoStudent.total.notAchieved}</span><small>ไม่ผ่าน</small></div><div><span className="summary-number pending">{demoStudent.total.pending}</span><small>ยังไม่ตัดสิน</small></div></div><Button variant="outline" className="report-button"><Download size={16} />รายงานรายบุคคล</Button></CardContent></Card>
    <section className="verdict-context"><div><span className="context-dot" />ใช้เกณฑ์ปัจจุบัน: ระดับ M/P · ผ่านที่ 3.51 · ต้องผ่านทุก sub-PLO</div><button><ShieldCheck size={15} />ดู Rule snapshot</button></section>
    <section className="plo-verdict-list">{demoStudent.plos.map((plo, index) => <Card key={plo.code} className={`verdict-card ${openPlo === plo.code ? "is-open" : ""}`}><CardContent><button className="verdict-head" onClick={() => setOpenPlo(openPlo === plo.code ? "" : plo.code)}><div className="verdict-index"><span>{String(index + 1).padStart(2, "0")}</span><strong>{plo.code}</strong></div><div className="verdict-title"><h2>{plo.title}</h2><p>{plo.note}</p></div><div className="verdict-value"><strong>{plo.value?.toFixed(2) ?? "—"}</strong><span>/ 3.51</span></div><PloBadge status={plo.status} /><ChevronDown className="verdict-chevron" size={19} /></button>{openPlo === plo.code && <div className="evidence-drawer">{plo.code === "PLO2" ? <><div className="evidence-drawer-top"><div><p className="section-kicker">EXPLAINABLE VERDICT</p><h3>เหตุผลของคำตัดสิน</h3></div><span className="engine-tag"><Sparkles size={14} />คำนวณตามกฎ</span></div><div className="reason-callout"><strong>ไม่ผ่าน PLO2</strong> เนื่องจาก sub-PLO 2.1 มีค่าถ่วงน้ำหนัก 2.80 ซึ่งต่ำกว่าเกณฑ์ 3.51 แม้ sub-PLO อื่นจะผ่านแล้ว โดยใช้กฎ “ต้องผ่านทุก sub-PLO”</div><div className="evidence-thread"><span className="thread-line" />{demoStudent.evidence.map((item, itemIndex) => <div className="evidence-node" key={item.code}><span className="thread-node">{itemIndex + 1}</span><div className="evidence-sub"><strong>sub-PLO {item.code}</strong><small>{item.course} · {item.method}</small></div><div className="evidence-score"><strong>{item.score.toFixed(2)}</strong><span>ระดับสมรรถนะ</span></div><PloBadge status={item.verdict === "ผ่าน" ? "achieved" : "not_achieved"} compact /><Button variant="ghost" size="icon" aria-label="ดูรายละเอียดหลักฐาน"><Eye size={16} /></Button></div>)}</div><div className="verdict-actions"><Button variant="outline"><FileText size={16} />เปิดคะแนนดิบและหลักฐาน</Button><Button><RotateCcw size={16} />สร้างแผนซ่อมเสริม</Button></div></> : <div className="closed-evidence"><FileText size={22} /><div><strong>เปิดดูเส้นทางหลักฐานของ {plo.code}</strong><p>จะแสดง sub-PLO จุดวัด M/P คะแนนล่าสุด และหลักฐานที่สัมพันธ์กัน</p></div></div>}</div>}</CardContent></Card>)}</section>
  </div>;
}
